name: Gatsby Publish

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: node:14
    steps:
    - uses: actions/checkout@v2
    - working-directory: frontend
    - run: npm ci
    - run: npm run lint
    # - run: npm test # Uncomment if/when we actually add tests

  build:
    needs: [lint]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2
        env:
          GATSBY_MAPBOX_ACCESS_TOKEN: ${{ secrets.GATSBY_MAPBOX_ACCESS_TOKEN }}
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
